StateMachine@@NAME@@:
  Type: "AWS::StepFunctions::StateMachine"
  Properties:
    StateMachineName: @@NAME@@
    DefinitionString: |-
      @@STEPS@@
    RoleArn: !GetAtt [StatesExecutionRole, Arn]



